### ISSUE TITLE
[bug]cv2.findContours unpack error

### ISSUE THREAD

**Issue by ZoomQuiet** [akramhussein/pupil_plugin_marker_tracking_and_fixation_detection#1]
## env.

- Python 2.7.10
- OpenCV 2.4.13.2
- Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64

## error

Traceback (most recent call last):

      File "aruco_detector.py", line 231, in <module>
        detector(_pic)
      File "aruco_detector.py", line 189, in detector
        min_marker_perimeter=min_marker_perimeter
      File "/opt/data/uSEE/ETuSee/proto/test/M4ArUco/pupil_plugin_marker_tracking_and_fixation_detection/square_marker_detect_.py", line 161, in detect_markers
        , offset=(0,0)
    ValueError: need more than 2 values to unpack

## check

L157->[square_marker_detect_.py](https://github.com/akramhussein/pupil_plugin_marker_tracking_and_fixation_detection/blob/281e8d4c98c248112966e3acd9aeba202093b96b/square_marker_detect_.py#L157)

see: [Structural Analysis and Shape Descriptors — OpenCV 2.4.13.0 documentation](https://docs.opencv.org/2.4.13/modules/imgproc/doc/structural_analysis_and_shape_descriptors.html?highlight=findcontours#cv2.findContours)

point example:[samples/python2/contours.py](https://github.com/opencv/opencv/blob/249edb2c99fd05bd9ab18638368a164d263558c7/samples/python2/contours.py#L49)

    contours0, hierarchy = cv2.findContours( img.copy()
                                        , cv2.RETR_TREE
                                        , cv2.CHAIN_APPROX_SIMPLE
                                        )

## suggest

i fix :

    _img, contours, hierarchy = cv2.findContours(edges
        ...

as:

    contours, hierarchy = cv2.findContours(edges
        ...

working now,
guess usage old version?

**Comment by akramhussein** [comment]
Yes it's an old version.
